language: php

php:
- 7.3
- 7.4
- nightly

services:
- docker

notifications:
  email:
  - team@appwrite.io

install:
- docker-compose up -d
- sleep 10

script:
- docker ps
- vendor/bin/phpunit --configuration phpunit.xml
- vendor/bin/psalm --show-info=true
