language: php

php:
- 7.3
- 7.4
- nightly

services:
- docker

notifications:
  email:
  - team@appwrite.io

before_install:
- curl -fsSL https://get.docker.com | sh
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
- service docker start

install:
- docker-compose up -d
- sleep 10

script:
- docker ps
- vendor/bin/phpunit --configuration phpunit.xml
- vendor/bin/psalm --show-info=true
