language: php

php:
- 7.4
- 8.0
- nightly

services:
- docker

notifications:
  email:
  - team@appwrite.io

before_script: composer install --ignore-platform-reqs

install:
- docker-compose up -d
- sleep 10

script:
- docker ps
- vendor/bin/phpunit --configuration phpunit.xml tests
- vendor/bin/psalm --show-info=true
