version: '3.1'

services:

  tests:
    container_name: tests
    build:
      context: .
    networks:
      - database
    volumes:
      - ./:/usr/src/code

  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - database
    ports:
      - "8700:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  cockroach:
    image: cockroachdb/cockroach:v20.1.1
    container_name: cockroach
    command: start --insecure
    ports:
      - "8704:26257"
      - "8705:8080"
    networks:
      - database

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    networks:
      - database
    ports:
      - "8701:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  
  mongo:
    image: mongo:3.6
    container_name: mongo
    networks:
      - database
    ports:
      - "8702:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - database
    ports:
      - "8703:3307"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307

networks:
  database: